# directory roots (relative or absolute, user edits here only)
paths:
  ref:           ref/                           # 1000G, weights, baseline, genes
  gwas:          data/gwas/
  scdata:        data/singlecell/               # .h5ad or .rds
  metrics_csv:   data/metrics_csv/              # raw metric matrices
  metrics_bed:   data/metrics_bed/              # output of csv→bed
  results:       results/

window_kb: 100
n_quantiles: 5
n_ctrl_scdrs: 1000
gene_coord: ref/gene_coordinates.GRCh37.ensembl_v91.txt 
gwas: [EA3_Lee2018, BMI_Yengo2018]
singlecell_datasets: [Cheng_2018, Smillie_2019]
